### ISSUE TITLE
Prepare training rider

### ISSUE THREAD

**Issue by jobarratt** [datopian/ckanext-honduras#16]
# Description

Based on the exiting rider, review and prepare so suitable for Honduras

https://docs.google.com/document/d/1Wo2K1-j-DFngGFFqK7wGAsGv9cxZfjYk21011o3ej4k/edit

# Tasks

- [x] update rider
- [x] link to discovery form
- [x] approval by Product Owner

**Comment by michellecbox** [comment]
done by @jobarratt 
@pwalsh can you take a look?
