### ISSUE TITLE
Translate footer links for Spanish version of the Portal

### ISSUE THREAD

**Issue by michellecbox** [datopian/ckanext-honduras#32]
# Description
WB would like to update the list of links that is currently available on the footer of the portal. They have only provided the text in Spanish so it won't get translated to English for now.

Find texts below.
Note: Privacy Policy text link will be removed from the links section.

![image](https://user-images.githubusercontent.com/13909143/60194467-af1d4680-9839-11e9-9509-7b4765496fc3.png)

Left Column
1. About to **Datos Abiertos de Honduras**
2. Contact Us to **Contacto**
3.  Open Government to **Gobierno Abierto de Honduras**
4. -No text since this link will be removed-
Right Column
5.  About CNRA to **Publica Datos**
6. CKAN API to **Desarrolladores**
7. CKAN Association to **Guía de Datos Abiertos**

# Tasks

- [x] Implement task
- [ ] Share with WB
- [ ] Share with GoH

**Comment by michellecbox** [comment]
Adrià Mercader
@michellecbox  re translating the links on the footer, I assume they want to have the site both in Spanish and English? (if it's just Spanish we just change the values in the templates directly)

In that case we need to:
•  Mark all strings on the templates as translatable (whether they are in core or not), eg `{{ _('Open Government') }}`
• Generate translation files for the extension (this will include any strings that are not in core (docs: https://docs.ckan.org/en/2.8/extensions/translating-extensions.html)
• Create a Spanish translation file for the extension strings

Michelle Cortes 
@amercader thanks, for now it'll be just spanish since they didn't provide any other languages, I'll update the ticket and unassigned it from @tanvirchahal  since is more dev work then

**Comment by amercader** [comment]
This is done. I've set up the translations properly so future texts are easy to translate.

For reference the process is:

1. Wrap the texts in the templates with `{% trans %}Some text{% endtrans %}` or `{{ _('Some text') }}`. *Use English in the templates*
2. Extract the messages: `python setup.py extract_messages`
3. Edit the `ckanext/honduras/i18n/es/LC_MESSAGES/ckanext-honduras.po` file to add the Spanish translation
4. Compile the `.mo` file:  `python setup.py compile_catalog`

**Comment by michellecbox** [comment]
@amercader great, thanks!
